# Override para produção
replicaCount: 3

image:
  tag: "1.25-alpine"

env:
  APP_ENV: "production"
  DEBUG: "false"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  hosts:
    - host: simple-app.exemplo.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: simple-app-tls
      hosts:
        - simple-app.exemplo.com