apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  app.env: {{ .Values.env.APP_ENV | quote }}
  debug: {{ .Values.env.DEBUG | quote }}
  version: {{ .Values.app.version | quote }}