apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-web-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: simple-web-apps
  
  # Configuração da fonte
  source:
    repoURL: https://github.com/paulovitorcl/app-config.git
    path: helm-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: "1.25-alpine"
        - name: replicaCount
          value: "1"
  
  # Configuração do destino
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  # Configurações de sincronização
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    #   allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Configurações de revisão
  revisionHistoryLimit: 3